### ISSUE TITLE
if (is.na(options$out.width.px)) options$out.width.px = options$fig.width *  :    argument is of length zero

### ISSUE THREAD

**Issue by tschwarzl** [Bioconductor/BiocStyle#80] opened 2020-09-25 07:47 UTC
R-4.0.2  / BiocStyle 2.16.0 / Win10

When knitting a minimal html_document

```
1 ---
2 title: "test"
3 output: BiocStyle::html_document
4 ---
5
6  ```{r}
7  1
8  ```
```

one gets this error message

```
processing file: test.Rmd
Quitting from lines 7-8 (test.Rmd) 
Error in if (is.na(options$out.width.px)) options$out.width.px = options$fig.width *  : 
  argument is of length zero
Calls: <Anonymous> ... process_group.block -> call_block -> as.strict_list -> hook
Execution halted
```

**Comment by aoles** [comment] 2020-09-25 08:54
Duplicate of #78.

**Closed by aoles** 2020-09-25 08:54 UTC
